### ISSUE TITLE
Cannot upload packages bigger than 2GB

### ISSUE THREAD

**Issue by Schroedingers-Cat** [bagetter/BaGetter#101]
### Describe the bug
Uploading a nuget package bigger than 2GB (happens easily when the nuget package is a chocolatey package with embedded installer) causes the following error on the server (Linux, Docker, latest):
```
nuget-server |       Exception thrown during package upload
nuget-server |       System.IO.InvalidDataException: Multipart body length limit 2147483647 exceeded.
nuget-server |          at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
nuget-server |          at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
nuget-server |          at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
nuget-server |          at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
nuget-server |          at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
nuget-server |          at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
nuget-server |          at BaGetter.Web.HttpRequestExtensions.GetUploadStreamOrNullAsync(HttpRequest request, CancellationToken cancellationToken) in /src/BaGetter.Web/Extensions/HttpRequestExtensions.cs:line 20
nuget-server |          at BaGetter.Web.PackagePublishController.Upload(CancellationToken cancellationToken) in /src/BaGetter.Web/Controllers/PackagePublishController.cs:line 49
```

The problem already existed in the [original baget](https://github.com/loic-sharma/BaGet/issues/191) and was resolved by [increasing the MultipartBodyLengthLimit to 2GB](https://github.com/loic-sharma/BaGet/commit/1896e1be17474a2876afb46d35cee021c58ab56b).

### To Reproduce
1. Install like described [here](https://www.bagetter.com/docs/Installation/docker)
2. Create a package with more than 2GB of content (put a video file inside or a big installer)
3. Upload it via `nuget push packagename serverurl`
4. Observe bagetter's output

### Expected behavior
I'd expect the upload to succeed.

### Additional context
@Regenhardt made a test build with the [MultipartBodyLengthLimit increased to 8GB](https://gitlab.com/Regenhardt/BaGetter/-/commit/f55c931e71433285b9ddf1a3c725c9fa27bb6fed) which fixed the problem for nuget packages smaller than 8GB. We observed that for local file storage, there's no need to have 8GB of free RAM when uploading a package of 8GB because writing to that storage type happens via file streams. Therefore, it would make sense to make the limit configurable by the user. This is not the case for cloud storages like AWS so that configuration should only apply for the local file storage.

**Comment by Regenhardt** [comment]
Absolutely, go ahead and make a PR for the stream fix, thanks!
