### ISSUE TITLE
Show some stats like total amount of packages, version etc.

### ISSUE THREAD

**Issue by Schroedingers-Cat** [bagetter/BaGetter#102]
Users might want to know some general info about their BaGetter instance from the web UI. For instance, they might want to quickly look up its version. Or they might have uploaded an initial bunch of packages and want to check if the amount from their upload directory matches the amount of packages that landed on their server instance.

### Solution
I think it'd be useful to have a place for showing some general stats of the BaGetter instance, like:
- current version
- services being used/configured
- total amount of package IDs
- total amount of packages (package IDs and versions)

**Comment by seriouz** [comment]
Thank you for this great suggestion.
I really like the idea of seeing some stats of the BaGetter instance.

I am on board with the follwing stats:
- Current version
- Total amount of package
- Total amount of packages versions
- Services being used
- Disk usage (Folder size - Is this possible on S3?)

More ideas?
