### ISSUE TITLE
Released assets don't have correct version

### ISSUE THREAD

**Issue by FroggieFrog** [bagetter/BaGetter#109]
### Describe the bug
The binaries in the realeased assets don't have the corresponding version set.
They all have version `1.0.0.0`.
This is also true for the binaries inside the nuget packages.

### To Reproduce
1. download assets
2. check binaries

### Expected behavior
All binaries should have the same version as the corresponding release/tag.

### Screenshots
![grafik](https://github.com/bagetter/BaGetter/assets/6222752/ebb5e270-f362-41aa-8624-6f536f105c56)

### Additional context
Possible solutions:

- pass version as parameter to the `dotnet publish` in the release workflow (`-p:Version=$env:APP_VERSION`)
  - the version could be parsed from the tag (e.g. https://github.com/OrchardCMS/OrchardCore/blob/main/.github/workflows/release_ci.yml#L23)
- pass version as parameter to `dotnet pack` e.g. `dotnet pack -p:PackageVersion=2.1.0`
- use https://github.com/dotnet/Nerdbank.GitVersioning
- maybe use [SemVer](https://semver.org/)

**Comment by Regenhardt** [comment]
I like passing the tag to `dotnet publish`. That way the build outputs also have the version set correctly.
