### ISSUE TITLE
Add arm docker image support

### ISSUE THREAD

**Issue by cw-sarvesh** [bagetter/BaGetter#134]
### Is your feature request related to a problem? Please describe.
I tried to run the docker image on the arm/graviton machine but the existing image only supports AMD architecture

### Describe the solution you'd like
Create an arm docker image in a release pipeline

**Comment by seriouz** [comment]
Thank you for bringing this up! I'll look into this.

**Comment by seriouz** [comment]
@cw-sarvesh ARM (Linux) is now live - can you test it?

**Comment by SarveshMishra** [comment]
> @cw-sarvesh ARM (Linux) is now live - can you test it?

Yes, it's working fine. Thank you for fixing the GitHub action issue. 
I apologize for the delayed response.

**Comment by cw-sarvesh** [comment]
> @cw-sarvesh ARM (Linux) is now live - can you test it?

Yes, it's working fine. Thank you for fixing the GitHub action issue.
I apologize for the delayed response.
