### ISSUE TITLE
Package deprecation option

### ISSUE THREAD

**Issue by Wookashi** [bagetter/BaGetter#139]
We have some deprecated packages in bagetter. It will be nice to have option of deprecate old ones.
Something like in nuget.org (https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages)

Is it possible to add this option?

**Comment by Wookashi** [comment]
Ok, i see it in doscussion. Everything clear.

**Comment by jswolf19** [comment]
I'm not sure what discussion OP found, but there is another issue that is open #221 for anyone finding this issue first.
