### ISSUE TITLE
Use specific Directory.Build.props instead of global Directory.packages.props

### ISSUE THREAD

**Issue by Regenhardt** [bagetter/BaGetter#14]
I think the global Directory.packages.props shouldn't be used to add package dependencies, as this makes all those packages dependencies of all the projects, including test packages like moq and  xunit. Especially those should not be in the normal application projects. 

There are however already specific Directory.build.props in the /src and /test folders, I propose to use those to make sure all test projects and all source projects respectively use the same packages.

**Comment by bagetter-admin** [comment]
Directory.Packages.props only specifies the versions of the packages, it doesn't add the packages to the projects but ensures that versions are consistent across all the projects.

**Comment by Regenhardt** [comment]
Ah nice, didn't know that one.
