### ISSUE TITLE
Support private feeds

### ISSUE THREAD

**Issue by tomasfil** [bagetter/BaGetter#142]
### Describe the solution you'd like
https://github.com/loic-sharma/BaGet/issues/36

### Describe alternatives you've considered
Didnt find any open source nuget with private feeds

**Comment by seriouz** [comment]
This is a topic we know about and is definitely on our todo list.
But we have no date when it will be done.

If have interest you can give us a first draft as pr and we give our feedback.

**Comment by tomasfil** [comment]
@seriouz Draft is there. LMK if you want anything. I have tested it and everything seems to work without any breaking change. Its activated only by setting the Env variables (Docker compose, or appsettings directly)
