### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mubarak0443** [bagetter/BaGetter#149]
Hi ,

If i deploy Bagetter in IIS , do i need to take care anything additionally in Bagetter for HTTPS since we can configure everything related to HTTPS in IIS side only instead Bagetter settings.

Please help on this.

Thanks for your help ahead!

**Comment by Regenhardt** [comment]
Hi,

no need, if you set HTTPS binding, certificate, and URL in IIS manager, BaGetter will work with that.

**Comment by QingYi-Studio** [comment]
Is it possible to use HTTPS offline or locally?

I am currently using frp for remote access.

**Comment by Regenhardt** [comment]
@QingYi-Studio currently that is only possible using the IIS HTTPS binding, it will also work offline and locally. Without IIS it's not possible yet but there is a plan to let Bagetter itself use a and optionally create its own certificate.
