### ISSUE TITLE
Version v1.4.4 is wrongly tagged

### ISSUE THREAD

**Issue by viceice** [bagetter/BaGetter#162]
### Describe the bug
Version [v1.4.4](https://github.com/bagetter/BaGetter/releases/tag/v1.4.4) is tagged to the same commit as v1.3.3 instead of 44d14d78490610b92a5185adac8377327c0407e0

### To Reproduce
1. Got to https://github.com/bagetter/BaGetter/releases
2. Check the tag commits

### Expected behavior
v1.4.4 should be tagged to 44d14d78490610b92a5185adac8377327c0407e0

**Comment by Regenhardt** [comment]
You're right I tagged the wrong commit, thanks for noticing, I made v1.4.5 for the newest commit.
