### ISSUE TITLE
Packages should not be downloaded without API Key

### ISSUE THREAD

**Issue by devops-slash** [bagetter/BaGetter#168]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

I know, it doesn't support private feed yet but packages should not be downloadable without API Key atleast.

**Comment by Regenhardt** [comment]
As the nuget client does not support authenticating via API key, we won't implement that as a feature. 

We currently don't have much time, but one of if not the next thing we will add is private feeds via basic http authentication in #156, you can subscribe either there to be notified once it's merged, or to the BaGetter repo to get notified once the next release is created, or on discord to get notified when the update is released. Once that is done, we can talk about what's next, like adding the same authentication to the web GUI, which currently supports no authentication at all. 

If you have packages that cannot be available publicly, currently you'd have to restrict access to BaGetter to a local network and accessing that via VPN when working remotely. Or use a reverse proxy and add authentication on that layer.
