### ISSUE TITLE
Search with read-through caching return nothing

### ISSUE THREAD

**Issue by donbabbeo** [bagetter/BaGetter#194]
I've configured an IIS https proxy where i hosting BaGetter, i can reach it correctly both with webinterface and VS and i can find uploaded packages, but mirroring to "https://api.nuget.org/v3/index.json" is not working even if enabled.

**Comment by Regenhardt** [comment]
Hi, the read-through cache does not proxy search queries, just package downloads. This speeds up builds by not having to pull from nuget.org every time, but does not replace the mirrored package source entirely.
