### ISSUE TITLE
Publishing a new image to docker hub

### ISSUE THREAD

**Issue by seriouz** [bagetter/BaGetter#21]
It would be nice if we could manage to make releases here on GitHub and publish new images to Docker hub.
This could be done via GitHub Actions when a new release is made.
@bagetter-admin What do you think about that? Do you want to be the only person who can manage this? I don't like the idea of only one person who can manage the project. This is the problem what led to the death of BaGet in the first place.

**Comment by daghsentinel** [comment]
Agree with @seriouz here. And btw, thanks for letting me join the organization.

**Comment by KaiS2** [comment]
As someone looking to use BaGetter it would be great to have releases available and to see more than one maintainer on the project =)

**Comment by david-m77** [comment]
Is [bagetter/bagetter](https://hub.docker.com/r/bagetter/bagetter/tags) the corresponding Docker Hub repository?

**Comment by seriouz** [comment]
> Is [bagetter/bagetter](https://hub.docker.com/r/bagetter/bagetter/tags) the corresponding Docker Hub repository?

Yes it is.

**Comment by bagetter-admin** [comment]
There is a Publish workflow item that will push out to the docker repo. Let me know if you don’t see it in the Workflow list but as far as I can tell you should.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by seriouz** [comment]
@bagetter-admin Thanks i am seeing the actions and work flows. For the beginning we can work with that.
But what about the single source of failure what led to the problem of BaGet, that one person only can control every thing?
