### ISSUE TITLE
NuGet packages don't point to the fork website

### ISSUE THREAD

**Issue by jv42** [bagetter/BaGetter#25]
### Describe the bug

The NuGet packages for BaGetter point to BaGet for their Project website.

### To Reproduce
1. Open any package on nuget.org:  https://www.nuget.org/packages/BaGetter.Core
2. Look at the Project website link

### Expected behavior

The link points to https://www.bagetter.com/

### Additional context

Some changes were made to the relevant config file https://github.com/bagetter/BaGetter/blob/main/src/Directory.Build.props as part of #6 but they didn't touch some metadata that should be updated for the fork: Authors, Copyright, PackageProjectUrl.

**Comment by seriouz** [comment]
@jv42 I created a PR with the change. Thanks for sharing! 💙

**Comment by seriouz** [comment]
NuGet Page was updated! 🎉

**Comment by jv42** [comment]
That was quick 👍
