### ISSUE TITLE
Documentation for Docker seems to be wrong/incomplete

### ISSUE THREAD

**Issue by FroggieFrog** [bagetter/BaGetter#38]
### Describe the bug
The container can not start when using the commands inside the documentation, because the folder `bagetter-data/db` does not exist.

### To Reproduce
Do everything according to the documentation.
The `.env` will contain the path `/data/db/bagetter.db`.
Try to run the container -> error

### Expected behavior
The commands in the documentation are correct and the container can start.
Either by creating the directory `db` automatically or by adjusting the documentation to tell the user to create the `db` folder inside of `bagetter-data`.

I'm not sure if this is an error on my side or a general issue.
I tested this in this environment:
- Win 10 x64
- Powershell >7

**Comment by seriouz** [comment]
Thanks for the report. I'll look into this the coming days.

**Comment by seriouz** [comment]
@FroggieFrog May you try again with the latest version and report failure or success?

**Comment by FroggieFrog** [comment]
I can confirm that the issue is fixed. At least in my configurations and on my systems.
